{% set version = "7.0.8-43" %}

package:
  name: imagemagick
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/ImageMagick/ImageMagick/archive/{{ version }}.tar.gz
  sha256: 70ab9363491e36d53f23f45c3763eb796dce366720a676212159bd0a9e6be782

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - bzip2
    - fftw
    - fontconfig
    - freetype
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - jpeg
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl
    - pkg-config
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib
  run:
    - bzip2
    - fftw
    - fontconfig
    - freetype
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - jpeg
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl
    - pkg-config
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib

test:
  commands:
    - convert -version
    - Magick++-config --cflags
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.imagemagick.org/
  license: ImageMagick
  license_file: LICENSE
  summary: 'Software suite to create, edit, compose, or convert bitmap images.'

extra:
  recipe-maintainers:
    - ocefpaf
    - halldc
