travis:
  secure:
    BINSTAR_TOKEN: omQXcKhccElCkoI/6txAiYkD7V/UgWWnyGeJGeO3mA1gOO8UqkP79gMUJ+XgVuOKP571BbFMdG5zUdzEhS7VGhduZHqexFxTYMhQetCoJGTKjPirZKiliNzGUqhIj7nDpc+DZO8IfOZ+3UDEN1cWCF1ALqsYoXNt5TO2cB6K3TLnICxlDhD+T70PHTVLto2pdRnc5Otn9QW1AxaBDcnbb8E87k9zo86N4/hxit2QCo5dPJk1C8Va8guKhWUsi8ffyi9xlNysHJQmCvEDN9qfagINrQv+91JeXRL6PC3l/1/voHtUfCxRsE0E01Zz3cghRqgu34FWUVPRokgyOxk7dm1032Zp1C3hUysrwlaQTvaaOzWYP6SHg1EZO+H/Kr7zXsSiafsSXAy/QDq5Rm4aMVPol842oMT1PFywGvKE00uw0jSSvUS7tGoDoeGxt1LtggBDRzJkRmqcLVrBSphFbus+n/rQY+x/o9W183PXxO4s1KtKha0KiiAv1A08cA/AbqDsm2XdsR/Pv+ywP7nCT7c3A/PSTVGCrDnqsL9/6JQJ8vAJRY0Gf1pEjobWxtkmTLd6LnqFgoHYnZ7zvkw4zEbcdkX3RMUX4ZPiy/earPYMNMkarbaAxeuz8a1nck7WGbvs2JOk6XyjxItN7k/NJPEK8haamulZAXSdr9pHbPA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
