travis:
  secure:
    BINSTAR_TOKEN: L4tznU8o0zCbApoUMOi172+Cw6avsZAeCBQGcySpHMjbYZeqOVYzFEG9U2K5i0zw3vJgvW+AMQJVqlJyPiyaAu0ug4enJsP0jWK39jrWvVeUhrBwrQd1m7EB/eTaPC+/LTNgIUG+7KYIToa4wL/3H2B1JxGiDB+qHnoL3l14AIxYEMxOjIQ8BpwD0jlDvvHTBhXph5g3NCXuRhDdGELH/HaMx1gC1rFD4oYUj5lLi3wgiLLC65dnhs8nq7bp5pVNhWuJ009VDKsuO1SGcoj3MvsYI14VsISP9ug6hJlkIfyuCOkBFB9q19HYuMVZDwmXQwRXicDQEEGGnkaQhIaa2bYY0SlTJRmPbsxUNgfbsJfJVNPC8LqPfsyc5iI9mNL6DQO3QLYUFDb4WitGMSvQpKUvLM7wfAkRO64VTqLRyN/AAO7+nvutwgMs0P/76yKy3JacSwKYZ7P2SpuwSEGUZMIOdKX+KoCzHI8g7ard2G/jKC5Kca3F/gGigz/5+MNwJq4n0p78SsJHOOysCvC0tQh1THALbPweX6WEL1YI6UO3yKhW57b5BYoLS4mK6lkCnz36pnsnfuSFMTHv+NgKgdpvjZMxAMWfZX0fVJSaFR1IrUDngavVIZXk1aS38noQDnnwwCyjAZsN5xCuE1LBNaik8FhCf4TIZQorO2PgbDU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
