travis:
  secure:
    BINSTAR_TOKEN: jirdN5NHJ71oxsqiFCjWF3hnDGT269h81vk5luy8l7apjaeoP6cy+gf0r3FhXAfeKFgU/m4vJ5U08OpSURydf8fcGXDQteUWE16z/IbZVAJJHO0oQFFveff2XcBTVCWwZS/oJIbTG689GJzokU6TpQw3ojPTEqKJtflPYtu09KFkC30SEduvhHdU4E5yNGqFNn1xaNnelMeC4aoWxElY0OAK2bFOnNyX7EXPKgpMIqBCW9/n5Ns9elvCx16ENrjM6orz8DSUGzSenYeccsXTwbt3DOQSzFdOshEcgtPBnbJcgoKdmRUkJJw6PLX4pOx5Ov2baK8+kjemwiIluva1/NvU3tAmpzez29QyzNmcRFX4MzJ71kfrEOLVMKfwEXOvdVu01w3RNUXbnQj8Hihyfl6gKAGwqzLKxZIcXBtkBNQkz8wdXkdQs9WsI0CPjawe3OSimo2DMYP7hy63Ql5JpB1mcD5KsJ7u//q8idxEBUJ5S8mtdYcfXscmnoCdFLBx3ze3fYcwvNfySDADsGaoFhS7eRTl2y0MJhhUUYKyadlA2pN46SCcPabKoWkMRd9DmaZ/WQEGyeqHs98UgqIo+TavcKXqJeMWOGsAHH72mdBoMBaLhozUPtbAgpS95r5nVYB/SfAGZSeng3vHOEWOK9TruF1PTSAMAdN+M5U035Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
